<a href="https://colab.research.google.com/github/aswathim3844/paatshala-assessment/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix
-------------------------------------------------------------------------------------------------

In [ ]:
import numpy as np
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
x1=np.reshape(x,(4,10))
x1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
x1[3:4]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

2.Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [ ]:
A=np.full((3,3),5)
A

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
B=np.arange(1,10).reshape(3,3)
display(B)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
C=np.add(A,B)
C

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
D = np.multiply(A,B)
D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
D1=np.transpose(D)
D1

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.

In [ ]:
E=np.random.randint(10,100,size=15)
E


array([71, 78, 41, 92, 10, 17, 13, 85, 83, 11, 60, 68, 69, 19, 65])

In [ ]:
updated=np.where(E>51,-1,E)
updated

array([-1, -1, 41, -1, 10, 17, 13, -1, -1, 11, -1, -1, -1, 19, -1])

In [ ]:
np.sum(updated==-1)

np.int64(9)

4 .Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:

In [ ]:
F=np.random.random((5,4))
F

array([[0.31739657, 0.52554246, 0.25763395, 0.71431004],
       [0.3788165 , 0.63871848, 0.5860855 , 0.91999964],
       [0.39890242, 0.40740551, 0.5785003 , 0.17851866],
       [0.62254945, 0.15540771, 0.14316536, 0.71882892],
       [0.03042306, 0.06104198, 0.59443334, 0.1557181 ]])

In [ ]:
row_sum=np.sum(F,axis=1)
np.argmax(row_sum)

np.int64(1)

In [ ]:
min_row=np.min(F,axis=1,keepdims=True)
max_row=np.max(F,axis=1,keepdims=True)
normalized=(F-min_row)/(max_row-min_row)
normalized

array([[0.13086436, 0.58664887, 0.        , 1.        ],
       [0.        , 0.48024775, 0.38299234, 1.        ],
       [0.55098468, 0.5722434 , 1.        , 0.        ],
       [0.83275046, 0.02126651, 0.        , 1.        ],
       [0.        , 0.05428788, 1.        , 0.22215027]])

5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements,counts=np.unique(arr,return_counts=True)
print(unique_elements)
print(counts)


[1 3 5 7 9]
[2 2 3 1 1]


In [ ]:
duplicate_elements=unique_elements[counts > 1]
duplicate_elements

array([1, 3, 5])

6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

In [ ]:
G=np.arange(1,37).reshape(6,6)
G

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
middle=G[1:5,1:5]
middle

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [ ]:
even=middle[middle%2==0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [ ]:
even.reshape(2,4)

array([[ 8, 10, 14, 16],
       [20, 22, 26, 28]])

7. Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [ ]:
H=np.arange(0,12).reshape(3,4)
H

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
H.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
H.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
H.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

8 . Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
new = np.array([[5, 6]])
new_row = np.append(a, new, axis=0)
new_row



array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:

newc = np.array([7, 8, 9]).reshape(3, 1)
new_col = np.append(new_row, newc, axis=1)
display(new_col)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d=np.concatenate([a,b,c])
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d_reshape=d.reshape((3,3))
d_reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d_diagonal=np.diag(d_reshape)
d_diagonal

array([1, 5, 9])

10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [ ]:
j=np.arange(1,20)

In [ ]:
h=j[(j%3==0)| (j%5==0)]
h

array([ 3,  5,  6,  9, 10, 12, 15, 18])

In [ ]:
h.size

8